version: '3' # composeファイルのバージョン
services:
  boiler-plate: # サービス名
    container_name: todo_app
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./Dockerfile
    volumes: # マウントディレクトリ
      - ./boiler-plate:/go/src/github.com/boiler-plate
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./.go.env
    environment:
      - TZ=Asia/Tokyo